"""OBJ file writer and traffic JSON exporter."""

import json
from typing import List, Tuple
import numpy as np

from .geometry import Mesh


def write_obj(objects: List[Tuple[str, Mesh]], filepath: str, scale: float = 1.0) -> None:
    """Write a list of (name, mesh) pairs to an OBJ file.

    All vertex coordinates are multiplied by `scale` before writing.
    """
    lines = ["# Generated by procity", f"# scale={scale}", ""]

    v_offset = 1  # OBJ indices are 1-based

    for name, mesh in objects:
        if not len(mesh.vertices) or not len(mesh.faces):
            continue

        lines.append(f"o {name}")
        verts = mesh.vertices * scale
        for vx, vy, vz in verts:
            lines.append(f"v {vx:.6f} {vy:.6f} {vz:.6f}")
        for fa, fb, fc in mesh.faces:
            a, b, c = fa + v_offset, fb + v_offset, fc + v_offset
            lines.append(f"f {a} {b} {c}")
        lines.append("")

        v_offset += len(mesh.vertices)

    with open(filepath, "w") as fh:
        fh.write("\n".join(lines))


def write_traffic_json(segments: list, filepath: str, street_width_scaled: float) -> None:
    """Write road segments as JSON for the Three.js traffic simulation.

    Each segment is a dict: {start:[x,y,z], end:[x,y,z], type:str}.
    All coordinates are already in scaled (OBJ) units.
    street_width_scaled is also in OBJ units and used by the viewer to size cars.
    """
    data = {
        "street_width": street_width_scaled,
        "segments": segments,
    }
    with open(filepath, "w") as fh:
        json.dump(data, fh)
